# Classificação

Instalando requisitos

In [1]:
%pip install -r ./app/requirements.txt -q
%pip install pandas -q
%pip install scikit-learn -q
%pip install tensorflow -q
%pip install numpy -q

You should consider upgrading via the '/mnt/home/henrique/Repositorios_Git/GitHub.com/Henriquemcc/Ciencia da Computacao/Trabalho_Pratico_-_Processamento_e_Analise_de_Imagens_-_2024-1/develop_henrique_2024_05_27/venv/bin/python -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.
You should consider upgrading via the '/mnt/home/henrique/Repositorios_Git/GitHub.com/Henriquemcc/Ciencia da Computacao/Trabalho_Pratico_-_Processamento_e_Analise_de_Imagens_-_2024-1/develop_henrique_2024_05_27/venv/bin/python -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.
You should consider upgrading via the '/mnt/home/henrique/Repositorios_Git/GitHub.com/Henriquemcc/Ciencia da Computacao/Trabalho_Pratico_-_Processamento_e_Analise_de_Imagens_-_2024-1/develop_henrique_2024_05_27/venv/bin/python -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.
You 

Importando requisitos

In [10]:
from app.modelo.imagem_rgb import ImagemRGB
import sklearn.model_selection
import pandas
import tensorflow
import os
import numpy
import pickle
import random

Definindo variáveis

In [4]:
image_directory = os.path.join(os.getcwd(), 'dataset_converted')
num_classes = 6

Abrindo base de dados

In [5]:
data_frame = pandas.read_csv("classifications.csv")

In [17]:

data_frame['random'] = data_frame[data_frame.columns[0]].apply(lambda _: random.random())

In [19]:
data_frame.sort_values(
    by='random',
    inplace=True
)

In [21]:
data_frame

image_id                        image_filename  \
4625        226  199ea9d75d6266bcc1be87995de6a70a.png   
442         394  f1662645f23a20ea9806ca8c6d655fba.png   
2426        323  502a16718f0316c85196c0e491f37fd3.png   
8466         75  458d0586e1dc5d723b54924fa1a75ab1.png   
8664         71  c02c490c04b16068d3d7b0fad37c12e6.png   
...         ...                                   ...   
3958        250  539a88e6ce009eee5398bdbada60ff23.png   
6883        127  c22f24fa5dc7c8d99c2d2ba5e293960c.png   
10013        48  c7c3f56a4d110b49099830b0f65251a3.png   
8691         71  c02c490c04b16068d3d7b0fad37c12e6.png   
2558        315  c1d551f467cac1389043740557caae1f.png   

                          image_doi  cell_id  \
4625   10.6084/m9.figshare.12230315     4626   
442    10.6084/m9.figshare.12230888      443   
2426   10.6084/m9.figshare.12230633     2427   
8466   10.6084/m9.figshare.12229751     8467   
8664   10.6084/m9.figshare.12229739     8665   
...                             ...      ...   
3958   10.6084/m9.figshare.12230402     3959   
6883   10.6084/m9.figshare.12229973     6884   
10013  10.6084/m9.figshare.12229670    10014   
8691   10.6084/m9.figshare.12229739     8692   
2558   10.6084/m9.figshare.12230606     2559   

                           bethesda_system  nucleus_x  nucleus_y    random  
4625   Negative for intraepithelial lesion        506        167  0.000238  
442    Negative for intraepithelial lesion       1047        767  0.000256  
2426                                  LSIL        750        566  0.000287  
8466                                  HSIL        491        457  0.000297  
8664                                  HSIL       1052        441  0.000631  
...                                    ...        ...        ...       ...  
3958   Negative for intraepithelial lesion        753        792  0.999597  
6883   Negative for intraepithelial lesion        779        539  0.999685  
10013                                ASC-H       1181        585  0.999757  
8691                                  HSIL        513        763  0.999779  
2558   Negative for intraepithelial lesion       1085        512  0.999983  

[11534 rows x 8 columns]

Separando o x

In [8]:
x = []
for index, row in data_frame.iterrows():
    x.append(os.path.join(image_directory, row['bethesda_system'], "{}.png".format(row['cell_id'])))
x = pandas.array(x)

In [9]:
x

<StringArray>
[                                    '/mnt/home/henrique/Repositorios_Git/GitHub.com/Henriquemcc/Ciencia da Computacao/Trabalho_Pratico_-_Processamento_e_Analise_de_Imagens_-_2024-1/develop_henrique_2024_05_27/dataset_converted/SCC/1.png',
                                     '/mnt/home/henrique/Repositorios_Git/GitHub.com/Henriquemcc/Ciencia da Computacao/Trabalho_Pratico_-_Processamento_e_Analise_de_Imagens_-_2024-1/develop_henrique_2024_05_27/dataset_converted/SCC/2.png',
                                     '/mnt/home/henrique/Repositorios_Git/GitHub.com/Henriquemcc/Ciencia da Computacao/Trabalho_Pratico_-_Processamento_e_Analise_de_Imagens_-_2024-1/develop_henrique_2024_05_27/dataset_converted/SCC/3.png',
                                     '/mnt/home/henrique/Repositorios_Git/GitHub.com/Henriquemcc/Ciencia da Computacao/Trabalho_Pratico_-_Processamento_e_Analise_de_Imagens_-_2024-1/develop_henrique_2024_05_27/dataset_converted/SCC/4.png',
     '/mnt/home/henrique/R

In [24]:
x.shape

(11534,)

Separando o y

In [25]:
y = data_frame.iloc[:, 4].values
label_encoder = sklearn.preprocessing.LabelEncoder()
y = label_encoder.fit_transform(y)

In [26]:
type(y)

numpy.ndarray

In [27]:
y

array([4, 4, 3, ..., 0, 2, 4])

Separando o conjunto de treino e teste

In [28]:
x_train, x_test, y_train, y_test = sklearn.model_selection.train_test_split(x, y)

In [29]:
x_train[0]

'/mnt/home/henrique/Repositorios_Git/GitHub.com/Henriquemcc/Ciencia da Computacao/Trabalho_Pratico_-_Processamento_e_Analise_de_Imagens_-_2024-1/develop_henrique_2024_05_27/dataset_converted/Negative for intraepithelial lesion/4981.png'

In [30]:
y_train[1]

4

In [31]:
y_train

array([2, 4, 3, ..., 4, 4, 4])

Exportando x_test, x_train, y_test, y_train para um arquivo externo

In [15]:
with open('data.pkl', mode='wb') as file:
    pickle.dump([x_train, x_test, y_train, y_test], file)

# Aplicando o ResNet50

Construindo o modelo

In [22]:
input_tensor = tensorflow.keras.layers.Input(shape=(100, 100, 3))
modelo_base = tensorflow.keras.applications.resnet50.ResNet50(weights='imagenet', include_top=False, input_tensor=input_tensor)
mbo = modelo_base.output
mbo = tensorflow.keras.layers.GlobalAveragePooling2D()(mbo)
mbo = tensorflow.keras.layers.Dense(1024, activation='relu')(mbo)
predicoes = tensorflow.keras.layers.Dense(num_classes, activation='softmax')(mbo)

modelo = tensorflow.keras.models.Model(inputs=modelo_base.input, outputs=predicoes)

for layer in modelo_base.layers:
    layer.trainable = False

2024-05-29 10:20:02.787378: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-05-29 10:20:02.788496: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2251] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


Compilando

In [17]:
modelo.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy', 'recall', 'precision'])

Treinando o modelo

In [18]:
def preprocessar_imagem(imagem):
    if isinstance(imagem, numpy.ndarray):
        imagem = imagem/255.0
    else:
        raise ValueError("Imagem deve ser um numpy array")
    
    imagem = tensorflow.convert_to_tensor(imagem, dtype=tensorflow.float32)
    imagem = tensorflow.expand_dims(imagem, axis=0)
    return imagem

In [19]:
for index, image_path in enumerate(x_train):
    if (os.path.exists(image_path)):
        imagem_rgb = ImagemRGB.from_file(image_path)
        imagem_preprocessada = preprocessar_imagem(imagem_rgb.matriz)
        label = tensorflow.keras.utils.to_categorical(y_train[index], num_classes)
        label = tensorflow.convert_to_tensor(label, dtype=tensorflow.int8)
        label = tensorflow.expand_dims(label, axis=0)
        modelo.fit(x=numpy.array(imagem_preprocessada), y=label)

1/1 ━━━━━━━━━━━━━━━━━━━━ 11s 11s/step - accuracy: 0.0000e+00 - loss: 1.7459 - precision: 0.0000e+00 - recall: 0.0000e+00
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step - accuracy: 0.0000e+00 - loss: 7.2190 - precision: 0.0000e+00 - recall: 0.0000e+00
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step - accuracy: 0.0000e+00 - loss: 4.2692 - precision: 0.0000e+00 - recall: 0.0000e+00
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step - accuracy: 1.0000 - loss: 0.4656 - precision: 1.0000 - recall: 1.0000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - accuracy: 0.0000e+00 - loss: 5.3525 - precision: 0.0000e+00 - recall: 0.0000e+00
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - accuracy: 1.0000 - loss: 0.0030 - precision: 1.0000 - recall: 1.0000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step - accuracy: 0.0000e+00 - loss: 13.0156 - precision: 0.0000e+00 - recall: 0.0000e+00
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step - accuracy: 1.0000 - loss: 0.0014 - precision: 1.0000 - recall: 1.0000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 1.0000 - l

Exportando o modelo treinado

In [20]:
modelo.save('modelo.keras')

Exportando os pesos

In [ ]:
modelo.save_weights('pesos.weights.h5')

Testando o modelo

In [24]:
predicoes = []
for index, image_path in enumerate(x_test):
    if (os.path.exists(image_path)):
        imagem_rgb = ImagemRGB.from_file(image_path)
        imagem_preprocessada = preprocessar_imagem(imagem_rgb.matriz)
        predicao = modelo.predict(imagem_preprocessada)
        predicoes.append(predicao)
predicoes = numpy.array(predicoes)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step
1/1 ━━━━━━━

Exportando as predições

In [25]:
with open('predicoes.pkl', mode='wb') as file:
    pickle.dump(predicoes, file)

In [26]:
predicoes

array([[[0.02351419, 0.08161768, 0.08058541, 0.10495577, 0.6956503 ,
         0.01367676]],

       [[0.0210823 , 0.0771265 , 0.0759612 , 0.09986185, 0.7139601 ,
         0.01200797]],

       [[0.01867094, 0.07226446, 0.07078291, 0.09453884, 0.7332476 ,
         0.01049528]],

       ...,

       [[0.0176205 , 0.06964742, 0.06767683, 0.09263962, 0.74242705,
         0.00998859]],

       [[0.01694301, 0.06823891, 0.06617898, 0.09090581, 0.74814814,
         0.00958524]],

       [[0.02004587, 0.07478126, 0.07307739, 0.09809575, 0.7224454 ,
         0.01155424]]], dtype=float32)

In [27]:
import sklearn.metrics

In [31]:
predicoes.shape

(1416, 1, 6)

In [30]:
y_test.shape

(2884,)

In [29]:
sklearn.metrics.classification_report(y_teste, predicoes)

NameError: name 'y_teste' is not defined