Importando requisitos

In [3]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.applications.resnet50 import preprocess_input
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Input

Criando uma imagem RGB aleatória

In [4]:
# Example RGB image as a numpy array (shape: (100, 100, 3))
rgb_image = np.random.rand(100, 100, 3) * 255  # Random image for illustration
rgb_image = rgb_image.astype(np.uint8)

Preprocessando a imagem

In [5]:
# Step 1: Preprocess the image
def preprocess_image(image):
    # Ensure the image is a numpy array
    if isinstance(image, np.ndarray):
        # Normalize image (assuming the image is in the range [0, 255])
        image = image / 255.0
    else:
        raise ValueError("The image should be a numpy array.")
    
    # Convert image to a tensor and add batch dimension
    image = tf.convert_to_tensor(image, dtype=tf.float32)
    image = tf.expand_dims(image, axis=0)  # Add batch dimension
    return image

In [6]:
preprocessed_image = preprocess_image(rgb_image)

Preparando o label

In [7]:
# Step 2: Prepare the label
# Example label for classification (assuming 10 classes)
label = 3  # Example label
num_classes = 10
label = to_categorical(label, num_classes=num_classes)  # One-hot encode the label
label = tf.convert_to_tensor(label, dtype=tf.float32)
label = tf.expand_dims(label, axis=0)  # Add batch dimension

Criando o modelo

In [8]:
# Step 3: Create the model
input_tensor = Input(shape=(100, 100, 3))
base_model = ResNet50(weights='imagenet', include_top=False, input_tensor=input_tensor)
x = base_model.output
x = GlobalAveragePooling2D()(x)  # Add global average pooling layer
x = Dense(1024, activation='relu')(x)  # Add a fully connected layer
predictions = Dense(num_classes, activation='softmax')(x)  # Add output layer

model = Model(inputs=base_model.input, outputs=predictions)

# Optionally, freeze the base model layers to fine-tune only the top layers
for layer in base_model.layers:
    layer.trainable = False

Compilando o modelo

In [9]:
# Step 4: Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

Treinando o modelo

In [10]:
# Step 5: Train the model
model.fit(preprocessed_image, label, epochs=1)  # Train on the single image and label

1/1 ━━━━━━━━━━━━━━━━━━━━ 6s 6s/step - accuracy: 0.0000e+00 - loss: 2.7906


In [11]:
model

<Functional name=functional_3, built=True>

In [12]:
preprocessed_image

<tf.Tensor: shape=(1, 100, 100, 3), dtype=float32, numpy=
array([[[[0.56078434, 0.48235294, 0.6431373 ],
         [0.60784316, 0.85490197, 0.7176471 ],
         [0.78039217, 0.46666667, 0.11764706],
         ...,
         [0.89411765, 0.654902  , 0.8235294 ],
         [0.07843138, 0.60784316, 0.16862746],
         [0.03921569, 0.43529412, 0.8117647 ]],

        [[0.11764706, 0.32941177, 0.4627451 ],
         [0.5254902 , 0.13725491, 0.38431373],
         [0.9529412 , 0.5176471 , 0.3372549 ],
         ...,
         [0.9137255 , 0.5176471 , 0.03921569],
         [0.6392157 , 0.8       , 0.99607843],
         [0.40392157, 0.8666667 , 0.38431373]],

        [[0.10196079, 0.08627451, 0.10588235],
         [0.49019608, 0.90588236, 0.76862746],
         [0.9764706 , 0.11372549, 0.5647059 ],
         ...,
         [0.7176471 , 0.4392157 , 0.7607843 ],
         [0.29411766, 0.1882353 , 0.9019608 ],
         [0.9490196 , 0.95686275, 0.21176471]],

        ...,

        [[0.12941177, 0.8235294 , 

In [13]:
label

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]], dtype=float32)>