# Como converter uma imagem para uma Matriz RGB

In [1]:
!pip install Pillow

Defaulting to user installation because normal site-packages is not writeable
distutils: /home/henrique/.local/lib/python3.9/site-packages
sysconfig: /home/henrique/.local/lib64/python3.9/site-packages
user = True
home = None
root = None
prefix = None


In [2]:
import PIL.Image
import numpy

In [8]:
imagem = PIL.Image.open('exemplo.png')

In [9]:
imgagem_rgb = imagem.convert('RGB')

In [10]:
matriz_rgb = numpy.array(imgagem_rgb)

In [11]:
matriz_rgb

array([[[142, 219, 193],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [142, 219, 193],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [142, 219, 193],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 25

In [19]:
matriz_rgb[0]

array([[142, 219, 193],
       [255, 255, 255],
       [255, 255, 255],
       [255, 255, 255],
       [255, 255, 255],
       [255, 255, 255],
       [255, 255, 255],
       [255, 255, 255],
       [255, 255, 255],
       [255, 255, 255],
       [255, 255, 255],
       [255, 255, 255],
       [255, 255, 255],
       [255, 255, 255],
       [255, 255, 255],
       [255, 255, 255]], dtype=uint8)

In [20]:
matriz_rgb[0][0]

array([142, 219, 193], dtype=uint8)

In [21]:
matriz_rgb[0][0][0]

142

In [15]:
type(matriz_rgb)

numpy.ndarray

In [18]:
matriz_rgb[:, :, 0]

array([[142, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 255],
       [255, 142, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 255],
       [255, 255, 142, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 255],
       [255, 255, 255, 142, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 255],
       [255, 255, 255, 142, 142, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 255],
       [255, 142, 142, 255, 255, 255, 255, 255, 255, 255, 142, 142, 255,
        255, 255, 255],
       [255, 255, 255, 255, 255, 255, 142, 255, 255, 255, 255, 255, 255,
        255, 255, 255],
       [142, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 255],
       [255, 255, 142, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 255],
       [255, 255, 142, 255, 25

# Como converter uma matriz RGB em uma matriz de tons de cinza

In [23]:
def rgb_to_grayscale(rgb_image):
    # Usar a fórmula da luminância para converter para tons de cinza
    # grayscale = 0.2989 * R + 0.5870 * G + 0.1140 * B
    grayscale_image = numpy.dot(rgb_image[...,:3], [0.2989, 0.5870, 0.1140])
    return grayscale_image

In [27]:
imagem_convertida = rgb_to_grayscale(matriz_rgb)

In [28]:
type(imagem_convertida)

numpy.ndarray

In [30]:
grayscale_image_pil = PIL.Image.fromarray(imagem_convertida.astype(numpy.uint8))

In [31]:
grayscale_image_pil.save('imagem_tons_de_cinza.jpg')